### ISSUE TITLE
Note that the ammunition definitions related to combo extended in BuildingsSecurity.Turrets.XML can affect the running of games without combo extended installed

### ISSUE THREAD

**Issue by SolEtStella** [sumghai/DefensiveMachineGunTurretPack#10]
When I shoot a turtle with a turret, it shows in the turtle's log that it has been hit by the turret. But the performance that was not hit (injury animation) and threw the following error:

Exception ticking Bullet_DMGT_50BMG3274737: System.NullReferenceException: Object reference not set to an instance of an object
[Ref AFDE3914] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch2 (string)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickList.Tick_Patch2 (Verse.TickList)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch2 (Verse.Game)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Play.Update_Patch1 (Verse.Root_Play)

**Comment by sumghai** [comment]
@Kazan-oc - You did not follow the provided bug reporting template, and provide the correct troubleshooting information (game version, mod version, minimum number of mods to reproduce the issue), so I am rejecting your report. Please follow the correct bug reporting format, and resubmit.

您没有遵循提供的错误报告模板，也没有提供正确的故障排除信息（游戏版本、MOD 版本、重现问题所需的最少 MOD 数量），因此我拒绝接受您的报告。请按照正确的错误报告格式重新提交。
