### ISSUE TITLE
Make the turrets a tradeable good

### ISSUE THREAD

**Issue by Cheel66** [sumghai/DefensiveMachineGunTurretPack#3]
Currently, the only way to use turrets from the DMGTP is to build them via the security tab once relevant research has been done. In CE, however, it's possible to buy the KPV, M240B, AGS-30 and flak from faction bases, as well as (rarely) get them as rewards for completing world missions. I think this had something to do with those turrets being items created at a machining table prior to installation, rather than security tab buildings (similar to the mortar, I think?).

**Comment by sumghai** [comment]
Already implemented in #2.

Turret tradeability has nothing to do with whether or not they were initially crafted from a Machining Table - rather, CE turrets were assigned to an item category that was then explicitly referenced by the stockgenerators in CE trader patches.

As per #2, I implemented something similar by assigning trade tags to each of the turrets, then referenced them in my own trader patches.
