### ISSUE TITLE
Turrets range is broken when using Combat Extended

### ISSUE THREAD

**Issue by ruPaladin** [sumghai/DefensiveMachineGunTurretPack#4]
In defs for MK19 stated range is 35, but in game it is 112.
I do not know what is the issue. But your values in "range" tags do not apply. I have tried to increase/descrease but I always get 112 range in game on MK19. Probably other turrets have the same issue.

**Comment by sumghai** [comment]
If I may hazard a guess, you are also running the original Combat Extended mod, which contains DMGTP compatibility patches that I wrote - the patch increases the range of all turrets to be more realistic and be in line with other CE turrets. Those particular patches are missing updates to the special display radius stat that draw the "max range circle" you usually find on turrets.

I am no longer maintaining the patches included in the original CE mod, so I would advise you to switch to using CE: FastTrack Edition instead, as the DMGTP patches included for those will fix this issue.

https://steamcommunity.com/sharedfiles/filedetails/?id=1865597143

(Conflict of Interest Declaration: I am an active member of the CE: FastTrack team)

**Comment by ruPaladin** [comment]
Since in About.xml CE:FT is still called as "Combat Extended", that was probably made for compatibility reasons. So it will be a better solution to add patches to this (DefensiveMachineGunTurretPack
) mod, instead of moving them into the particular CE fork or CE itself. Since there is "PatchOperationFindMod" which makes it compatible with both CE version without need to include patch into CE or CE:FT. Patches will be activated if any version of CE found. No need to include them in CE or CE:FT, but only to Defensive Machibe GUn Turret Pack.

**Comment by sumghai** [comment]
Unfortunately, I don't think the CE team will allow me to remove my patches from their mod, or make any meaningful changes to it.

I've updated the Steam Workshop description for DMGTP advising users to only use CE:FT, as I will be maintaining the patches there , but that's the best that I can do.

**Comment by ruPaladin** [comment]
I will try to implement your changes into original CE. Will it be ok?

**Comment by sumghai** [comment]
Sure thing!
