### ISSUE TITLE
M2HB Twin runs dry twice as fast as it probably should

### ISSUE THREAD

**Issue by flyfire2002** [sumghai/DefensiveMachineGunTurretPack#5]
From Defs/ThingDefs:

M2HB   10000 Fuel, 3 rnds burst, 1 fuel per shot;
M2HBT  20000 Fuel, 6 rnds burst, **2 fuel** per shot;

If we are to believe a barrel should have the same burst expectancy on either gun (apparent from the fuel amount and burst count), M2HBT fires half of bursts as M2HB does before needing refuel.

**Comment by sumghai** [comment]
Both barrels are firing at the same time, therefore the current implementation works as intended.
