### ISSUE TITLE
hi, i got some bug here

### ISSUE THREAD

**Issue by thienan865608** [sumghai/DefensiveMachineGunTurretPack#6]
hi, some reason, i dont know, long time i not play, but now, my turet cant hit anything,turet can fire but not hit, look like a accuracy = 0. Frist time the enemy is a little dog, i think is normal, but i try test with a raid, 2 turet cant even hit 1 :(((((
https://imgur.com/gallery/n5LhUga

**Comment by sumghai** [comment]
Please repost your issue using the proper bug reporting template.
